language: node_js
node_js:
- "10"
dist: trusty
sudo: false

branches:
  only:
  - master

cache:
  directories:
  - node_modules

install:
- npm install -g @angular/cli

script:
- npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/code-stats-ranking
  on:
    branch: master
