language: node_js
node_js:
- "9"
dist: trusty
sudo: false

branches:
  only:
  - master

cache:
  directories:
  - node_modules

install:
- npm install -g yarn

script:
- yarn lint
- yarn build --base-href http://www.jeseromero.com/code-stats-ranking/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/code-stats-ranking
  on:
    branch: master
